FROM bearstech/php-cli:7.0

ENV PHP_VERSION 7.0

USER root

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                ca-certificates \
                php-memcached \
                php-xdebug \
                php7.0-curl \
                php7.0-fpm \
                php7.0-gd \
                php7.0-json \
                php7.0-mbstring \
                php7.0-mysql \
                php7.0-xml \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  phpdismod \
               ftp \
               shmop \
               wddx \
               xdebug \
    &&  phpenmod \
              msgpack \
    &&  mkdir /var/log/php \
    &&  ln -sf /proc/1/fd/2 /var/log/php/php7.0-fpm.log \
    &&  ln -sf /proc/1/fd/2 /var/log/php/www.error.log \
    &&  ln -sf /proc/1/fd/1 /var/log/php/www.access.log \
    &&  ln -sf /dev/null    /var/log/php/www.slow.log \
    &&  ln -sf /proc/1/fd/2 /var/log/msmtp.log

COPY conf/www.conf /etc/php/7.0/fpm/pool.d/www.conf
COPY conf/php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf

RUN set -eux \
    &&  chmod 700 /etc/php/7.0/fpm/pool.d \
    &&  chmod 600 /etc/php/7.0/fpm/pool.d/www.conf \
    &&  chown -R www-data /etc/php/7.0/fpm/pool.d \
    &&  touch /etc/msmtprc \
    &&  chown www-data /etc/msmtprc \
    &&  chmod 640 /etc/msmtprc

LABEL sh.factory.probe.fpm.path=/__path

EXPOSE 9000

COPY entrypoint.sh /usr/local/bin/
USER www-data

ENTRYPOINT ["entrypoint"]
CMD ["/usr/sbin/php-fpm7.0"]
