FROM bearstech/debian:stretch

RUN apt-get update && apt-get install -y \
        ca-certificates \
        php-memcached \
        php-xdebug \
        php7.0-fpm \
        php7.0-gd \
        php7.0-json \
        php7.0-mbstring \
        php7.0-mysql \
        php7.0-xml \
        && rm -rf /var/lib/apt/lists/*

RUN phpdismod \
       ftp \
       shmop \
       wddx \
       xdebug

RUN mkdir /var/log/php && \
        ln -s /dev/stderr /var/log/php/php7.0-fpm.log && \
        ln -s /dev/stderr /var/log/php/www.error.log && \
        ln -s /dev/stdout /var/log/php/www.access.log && \
        ln -s /dev/null /var/log/php/www.log.slow

COPY conf/www.conf /etc/php/7.0/fpm/pool.d/www.conf
COPY conf/php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf

EXPOSE 9000

USER www-data
CMD /usr/sbin/php-fpm7.0
