FROM bearstech/debian:stretch

RUN apt-get update && \
        apt-get install -y --no-install-recommends \
                        ca-certificates \
                        php7.0-cli \
                        php7.0-gd \
                        php7.0-mbstring \
                        php7.0-xml \
                        && \
        rm -rf /var/lib/apt/lists/*

ARG uid=1000
RUN useradd php --uid ${uid} --shell /bin/bash
USER php
WORKDIR /home/php

CMD php
