FROM bearstech/debian:stretch

RUN apt-get update && apt-get install -y \
        ca-certificates \
        msmtp \
        php-memcached \
        php-xdebug \
        php7.0-fpm \
        php7.0-gd \
        php7.0-json \
        php7.0-mbstring \
        php7.0-mysql \
        php7.0-xml \
        && rm -rf /var/lib/apt/lists/*

RUN phpdismod \
       ftp \
       shmop \
       wddx \
       xdebug \
    && phpenmod \
       msgpack

RUN ln -s /usr/bin/msmtp /usr/local/bin/sendmail

RUN mkdir /var/log/php && \
        ln -sf /proc/1/fd/2 /var/log/php/php7.0-fpm.log && \
        ln -sf /proc/1/fd/2 /var/log/php/www.error.log && \
        ln -sf /proc/1/fd/1 /var/log/php/www.access.log && \
        ln -sf /dev/null    /var/log/php/www.slow.log && \
        ln -sf /proc/1/fd/2 /var/log/msmtp.log

COPY entrypoint /usr/local/bin/entrypoint
ENTRYPOINT ["entrypoint"]

COPY conf/www.conf /etc/php/7.0/fpm/pool.d/www.conf
COPY conf/php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf
RUN touch /etc/msmtprc && chmod 777 /etc/msmtprc

EXPOSE 9000

USER www-data
CMD /usr/sbin/php-fpm7.0
