FROM bearstech/php-cli:7.0

ENV PHP_VERSION 7.0
ENV DEBIAN_FRONTEND noninteractive

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                dumb-init \
                php-memcached \
                php-xdebug \
                php7.0-curl \
                php7.0-fpm \
                php7.0-gd \
                php7.0-json \
                php7.0-mbstring \
                php7.0-mysql \
                php7.0-xml \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  phpdismod \
               ftp \
               shmop \
               wddx \
               xdebug \
    &&  phpenmod \
              msgpack \
    &&  mkdir /var/log/php \
    &&  ln -sf /proc/1/fd/2 /var/log/php/php7.0-fpm.log \
    &&  ln -sf /proc/1/fd/2 /var/log/php/www.error.log \
    &&  ln -sf /proc/1/fd/1 /var/log/php/www.access.log \
    &&  ln -sf /proc/1/fd/2 /var/log/php/www.slow.log

COPY conf/php.ini /etc/php/7.0/fpm/php.ini
COPY conf/www.conf /opt/www.conf.tpl
COPY conf/php-fpm.conf /etc/php/7.0/fpm/php-fpm.conf

RUN set -eux \
    &&  chmod 777 /etc/php/7.0/fpm/pool.d \
    &&  chmod 444 /opt/www.conf.tpl \
    &&  rm -f /etc/php/7.0/fpm/pool.d/www.conf \
    #&&  chown -R www-data /etc/php/7.0/fpm/pool.d \
    &&  touch /etc/msmtprc \
    #&&  chown www-data /etc/msmtprc \
    &&  chmod 666 /etc/msmtprc

LABEL sh.factory.probe.fpm.path=/__status

EXPOSE 9000

COPY entrypoint.sh /usr/local/bin/

ENTRYPOINT ["entrypoint.sh"]
CMD ["dumb-init", "/usr/sbin/php-fpm7.0"]

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL com.bearstech.image.revision_date=${GIT_DATE}

LABEL org.opencontainers.image.authors=Bearstech

LABEL org.opencontainers.image.revision=${GIT_VERSION}
LABEL org.opencontainers.image.created=${BUILD_DATE}

LABEL org.opencontainers.image.url=https://github.com/factorysh/docker-php
LABEL org.opencontainers.image.source=https://github.com/factorysh/docker-php/blob/${GIT_VERSION}/Dockerfile.7.0
