FROM bearstech/debian:stretch

RUN apt-get update && apt-get install -y \
        curl \
        ca-certificates \
        apt-transport-https \
        lsb-release \
        ca-certificates \
        && rm -rf /var/lib/apt/lists/*

RUN cd /etc/apt/trusted.gpg.d && curl -o php-sury.gpg https://packages.sury.org/php/apt.gpg

RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" >> /etc/apt/sources.list.d/php-sury.list

RUN apt-get update && apt-get install -y \
        msmtp \
        php7.1-mysql \
        php7.1-curl \
        php7.1-json \
        php7.1-gd \
        php7.1-mcrypt \
        php7.1-intl \
        php7.1-mbstring \
        php7.1-xml \
        php7.1-zip \
        php7.1-fpm \
        php7.1-readline \
        && rm -rf /var/lib/apt/lists/*

RUN phpdismod \
       ftp \
       shmop \
       wddx

RUN ln -s /usr/bin/msmtp /usr/local/bin/sendmail

RUN mkdir /var/log/php && \
        ln -sf /proc/1/fd/2 /var/log/php/php7.1-fpm.log && \
        ln -sf /proc/1/fd/2 /var/log/php/www.error.log && \
        ln -sf /proc/1/fd/1 /var/log/php/www.access.log && \
        ln -sf /dev/null    /var/log/php/www.slow.log && \
        ln -sf /proc/1/fd/2 /var/log/msmtp.log

COPY entrypoint7.1 /usr/local/bin/entrypoint
ENTRYPOINT ["entrypoint"]

COPY conf/www.conf /etc/php/7.1/fpm/pool.d/www.conf
RUN chmod 700 /etc/php/7.1/fpm/pool.d && \
        chmod 600 /etc/php/7.1/fpm/pool.d/www.conf && \
        chown -R www-data /etc/php/7.1/fpm/pool.d

COPY conf/php7.1-fpm.conf /etc/php/7.1/fpm/php-fpm.conf
RUN touch /etc/msmtprc && chmod 777 /etc/msmtprc

EXPOSE 9000

USER www-data
CMD /usr/sbin/php-fpm7.1
