---

command:
    composer -V:
        exit-status: 0
        stdout:
            - "/(Composer version|Composer) {{ .Vars.composer_version }}/"
        stderr: []
    composer1 -V:
        exit-status: 0
        stdout:
            - "/Composer version {{ .Vars.composer1_version }}/"
        stderr: []
